print-status: True

api:
    name: Camera Stream
    extension: yml
    security:
        secret: default
    server:
        scheme: http
        port: 5000
        host: localhost
        base-url: /camera-stream-api
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

swagger:
    host: ${api.server.host}:${api.server.port}
    schemes: [${api.server.scheme}]
    info:
        title: ${api.name}
        version: 0.0.1
        description: It listen camera sources and streams it for client requests
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
